version: "3"

volumes:
  growth_hackers:

networks:
  hostnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

services:
  db:
    container_name: growth_hackers
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=growth_hackers
      - POSTGRES_USER=growth
      - POSTGRES_PASSWORD=growth
    ports:
      - "5432:5432"
    volumes:
      - growth_hackers:/var/lib/postgresql/data
    networks:
      hostnet:
    healthcheck:
      test: "pg_isready -U growth -d growth_hackers && psql --username=growth --list"
      timeout: 10s
      retries: 5

  db_setup:
    image: postgres
    restart: on-failure
    depends_on:
      - db
    command: ["bash", "-c", "PGPASSWORD=growth psql -h db -p 5432 -U growth -d growth_hackers -c \"drop schema if exists test cascade; create schema test\""]
    networks:
      hostnet:

